---
- name: preconfig
 #  become: true
  hosts: demo
  ignore_errors: true
  tasks:
    - name: install docker
      block:
        - name: get_universe
          apt_repository:
            repo: "deb http://us.archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }} universe"
            state: present          

        - name: install extra pkg
          apt:
            name:
              - apt-transport-https
              - ca-certificates
              - curl
              - gnupg
              - lsb-release
            update-cache: true
            cache_valid_time: 86400        
        - name: Add Dockerâ€™s official GPG key
          apt_key:
            url: https://download.docker.com/linux/ubuntu/gpg
            state: present
         

        - name: install ustable repo
          apt_repository:
            repo: > 
              deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu 
              {{ ansible_distribution_release }} stable 
            state: present
            update-cache: true
            filename: docker
        - name: install docker-ce
          apt:
            name: docker-ce
            update-cache: true
         
        - name: check docker install and reboot
          service:
            name: docker
            state: restarted
            enabled: true
      become: true     
    - name: get docker-compose
      block:
        - name: get last version dc
          uri:
            url: https://api.github.com/repos/docker/compose/releases/latest
            body_format: json
          register: page
        - name: install docker-compose
          get_url:
            url:  "https://github.com/docker/compose/releases/download/{{ page.json.tag_name }}/docker-compose-Linux-x86_64"
            dest: /usr/local/bin/docker-compose
            mode: 0755
      become: true    
    - name: end installation
      become: true  
      block:
      - name: add user to docker-group
        user:
          name: "{{ ansible_user }}"
          groups: docker
          append: true
      - name: reboot server
        reboot:



        
